config/routes.rb
Rails.application.routes.draw do

  mount Bootsy::Engine => '/bootsy', as: 'bootsy'
  resources :categories, only: [:show]

	namespace :casein do
		resources :page_contents
		resources :categories
	end

  root  to: "static_pages#home"

  get "contact" => "static_pages#contact", as: :contact
  get "privacy" => "static_pages#privacy", as: :privacy
  get "terms" => "static_pages#terms", as: :terms
  get "china_desk" => "static_pages#china_desk", as: :china_desk
  get "location/:area" => "static_pages#location", as: :location

end

app/models/category.rb
class Category < ActiveRecord::Base
  include Bootsy::Container

  acts_as_nested_set
end

app/models/page_content.rb
class PageContent < ActiveRecord::Base
  has_attached_file :image, styles: { medium: "255x123" }, default_url: "missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :load_categories
  before_action :load_contents
  before_action :set_locale

  CN_LOCALE = "zh-CN"

  def page_contents(*names)
    contents = PageContent.where("name IN (?)", names).all
    contents.each { |content| instance_variable_set("@#{content.name}", content) }
  end

  def load_categories
    @categories = Category.where(:parent_id => nil).order(:id => :asc).all
    @services = @categories.find{|category| category.name == "Services"}
    @sectors = @categories.find{|category| category.name == "Sectors"}
  end

  def load_contents
    page_contents("logo", "landline", "mobile", "address")
  end

  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
    @attr_suffix = "_cn" if params[:locale] == CN_LOCALE
  end
end

app/controllers/casein/categories_controller.rb
# Scaffolding generated by Casein v5.1.1.5

module Casein
  class CategoriesController < Casein::CaseinController

    ## optional filters for defining usage according to Casein::AdminUser access_levels
    # before_filter :needs_admin, :except => [:action1, :action2]
    # before_filter :needs_admin_or_current_user, :only => [:action1, :action2]

    def index
      @casein_page_title = "Categories"
  		@categories = Category.order(sort_order(:id)).paginate :page => params[:page]
    end

    def show
      @casein_page_title = "View category"
      @category = Category.find params[:id]
      @categories = Category.where("id != ?", params[:id]).all
    end

    def new
      @casein_page_title = "Add a new category"
    	@category = Category.new
      @categories = Category.all
    end

    def create
      @category = Category.new category_params

      if @category.save
        flash[:notice] = "Category created"
        redirect_to casein_categories_path
      else
        flash.now[:warning] = "There were problems when trying to create a new category"
        render :action => :new
      end
    end

    def update
      @casein_page_title = "Update category"

      if category_params[:parent_id].present?
        parent_category = Category.find category_params[:parent_id]
      end
      @category = Category.find params[:id]

      if @category.update_attributes(update_params)
        @category.move_to_child_of(parent_category) if parent_category
        flash[:notice] = "Category has been updated"
        redirect_to casein_categories_path
      else
        flash.now[:warning] = "There were problems when trying to update this category"
        render :action => :show
      end
    end

    def destroy
      @category = Category.find params[:id]

      @category.destroy
      flash[:notice] = "Category has been deleted"
      redirect_to casein_categories_path
    end

    private

      def category_params
        params.require(:category).permit(:name, :lft, :rgt, :parent_id,
         :name_cn, :context_cn, :bootsy_image_gallery_id)
      end

      def update_params
        params.require(:category).permit(:name, :context, :name_cn,
         :context_cn, :bootsy_image_gallery_id)
      end

  end
end

app/controllers/casein/page_contents_controller.rb
# Scaffolding generated by Casein v5.1.1.5

module Casein
  class PageContentsController < Casein::CaseinController

    ## optional filters for defining usage according to Casein::AdminUser access_levels
    # before_filter :needs_admin, :except => [:action1, :action2]
    # before_filter :needs_admin_or_current_user, :only => [:action1, :action2]

    def index
      @casein_page_title = 'Page contents'
  		@page_contents = PageContent.order(sort_order(:name)).paginate :page => params[:page]
    end

    def show
      @casein_page_title = 'View page content'
      @page_content = PageContent.find params[:id]
    end

    def new
      @casein_page_title = 'Add a new page content'
    	@page_content = PageContent.new
    end

    def create
      @page_content = PageContent.new page_content_params

      if @page_content.save
        flash[:notice] = 'Page content created'
        redirect_to casein_page_contents_path
      else
        flash.now[:warning] = 'There were problems when trying to create a new page content'
        render :action => :new
      end
    end

    def update
      @casein_page_title = 'Update page content'

      @page_content = PageContent.find params[:id]
      @page_content.image.destroy if params[:page_content][:image]
      if @page_content.update_attributes page_content_params
        flash[:notice] = 'Page content has been updated'
        redirect_to casein_page_contents_path
      else
        flash.now[:warning] = 'There were problems when trying to update this page content'
        render :action => :show
      end
    end

    def destroy
      @page_content = PageContent.find params[:id]

      @page_content.destroy
      flash[:notice] = 'Page content has been deleted'
      redirect_to casein_page_contents_path
    end

    private

      def page_content_params
        params.require(:page_content).permit(:name, :image, :context,
          :context_cn, :bootsy_image_gallery_id)
      end

  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def show
    @category = Category.find(params[:id])
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    page_contents("slogen", "home_intro")
  end

  def location
    @area = params[:area]
  end

  def contact
  end

  def terms
  end

  def privacy
  end

  def china_desk
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/casein/config_helper.rb
module Casein
  module ConfigHelper

    # Name of website or client — used throughout Casein.
    def casein_config_website_name
      'UKEI'
    end

    # Filename of logo image. Ideally, it should be a transparent PNG around 140x30px
    def casein_config_logo
      'rsg-logo-admin.jpg'
    end

    # The server hostname where Casein will run
    def casein_config_hostname
      if Rails.env.production?
        'http://ukei.herokuapp.com'
      else
        'http://0.0.0.0:3000'
      end
    end

    # The sender address used for email notifications
    def casein_config_email_from_address
      'donotreply@ukei.com'
    end

    # The initial page the user is shown after they sign in or click the logo. Probably this should be set to the first tab.
    # Do not point this at casein/index!
    def casein_config_dashboard_url
      url_for casein_categories_path
    end

    # A list of stylesheets to include. Do not remove the core casein/casein, but you can change the load order, if required.
    def casein_config_stylesheet_includes
      %w[casein/casein casein/custom]
    end

    # A list of JavaScript files to include. Do not remove the core casein/casein, but you can change the load order, if required.
    def casein_config_javascript_includes
      %w[casein/casein casein/custom]
    end

    def strip_casein_options options
      options.reject {|key, value| key.to_s.include? "casein_" }
    end

  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/casein/categories/_form.html.haml
/ Scaffolding generated by Casein v5.1.1.5
.row
  .col-lg-6
    = casein_text_field f, f.object, :name
  .col-lg-6
    = casein_select f, f.object, :parent_id, @categories.map { |p| [ "#{p.level} - #{p.name}", p.id ] }, { include_blank: true }

.row
  .col-lg-6
    = casein_text_field f, f.object, :name_cn

.row
  .col-lg-12
    = casein_bootsy_area f, f.object, :context, cols: "30", rows: "10"

.row
  .col-lg-12
    = casein_bootsy_area f, f.object, :context_cn, cols: "30", rows: "10"

app/views/casein/categories/_table.html.haml
/ Scaffolding generated by Casein v5.1.1.5
%table.table.table-striped.table-hover.table-condensed
  %thead
    %tr
      %th= casein_sort_link "Id", :id
      %th= casein_sort_link "Name", :name
      %th= casein_sort_link "NameCN", :name
      %th= casein_sort_link "Level", :name
      %th= casein_sort_link "Parent", :parent_id
      %th  
  - categories.each do |category|
    %tr
      %td= casein_table_cell_link category.id, casein_category_path(category)
      %td= casein_table_cell_link category.name, casein_category_path(category)
      %td= casein_table_cell_link category.name_cn, casein_category_path(category)
      %td= casein_table_cell_link category.level, casein_category_path(category)
      %td= casein_table_cell_link category.parent.try(:name), casein_category_path(category)
      %td.delete
        = link_to(casein_show_row_icon("trash"), casein_category_path(category), :method => :delete, :data => { :confirm => "Are you sure you want to delete this category?" })

app/views/casein/categories/index.html.haml
/ Scaffolding generated by Casein v5.1.1.5
%h2
  Categories#{casein_pagination_details @categories}
= render :partial => 'casein/categories/table', :locals => { :categories => @categories }
.text-center
  = will_paginate @categories
= content_for :sidebar do
  %li= link_to "#{casein_show_icon "plus-sign"}Add a new category".html_safe, new_casein_category_path

app/views/casein/categories/new.html.haml
/ Scaffolding generated by Casein v5.1.1.5
%h2 Add a new category
= form_for @category, :url => casein_categories_path do |f|
  = render :partial => 'casein/categories/form', :locals => { :f => f }
  %p.submits
    = link_to 'Cancel', casein_categories_path, :class => 'btn btn-mini btn-danger'
    = f.submit "Add new category", :class => "btn btn-mini btn-primary"
= content_for :sidebar do
  %li= link_to "#{casein_show_icon "th-list"}Back to list".html_safe, casein_categories_path

app/views/casein/categories/show.html.haml
/ Scaffolding generated by Casein v5.1.1.5
%h2 View category
= form_for @category, :url => casein_category_path(@category) do |f|
  = render :partial => 'casein/categories/form', :locals => { :f => f }
  %p.submits
    = link_to 'Cancel', casein_categories_path, :class => 'btn btn-mini btn-danger'
    = f.submit "Save changes", :class => "btn btn-mini btn-primary"
= content_for :sidebar do
  %li= link_to "#{casein_show_icon "th-list"}Back to list".html_safe, casein_categories_path

app/views/casein/layouts/_tab_navigation.html.erb
<li id="tab-categories">
  <%= link_to "Categories", casein_categories_path %>
</li>
<li id="tab-page_contents">
  <%= link_to "PageContents", casein_page_contents_path %>
</li>

app/views/casein/layouts/_top_navigation.html.erb
<li>
  <%= link_to "Visit site", casein_config_hostname, :target => "_blank" %>
</li>

app/views/casein/page_contents/_form.html.erb
<!-- Scaffolding generated by Casein v5.1.1.5 -->


<div class="row">
	<div class="col-lg-6">
		<%= casein_text_field f, f.object, :name %>
	</div>
	<div class="col-lg-6">
		<%= casein_file_field f, f.object, nil, :image %>
		<div class="well">
			<label>Preview</label>
			<%= image_tag(f.object.image.url(:medium), size: "64") %>
		</div>
	</div>
</div>

<div class="row">
	<div class="col-lg-12">
		<%= casein_text_area f, f.object, :context, rows: "5" %>
	</div>
</div>

<div class="row">
	<div class="col-lg-12">
		<%= casein_text_area f, f.object, :context_cn, rows: "5" %>
	</div>
</div>

app/views/casein/page_contents/_table.html.erb
<!-- Scaffolding generated by Casein v5.1.1.5 -->

<table class="table table-striped table-hover table-condensed">
	<thead>
		<tr>
			<th><%= casein_sort_link "Name", :name %></th>
			<th><%= casein_sort_link "Image", :image %></th>
			<th><%= casein_sort_link "Context", :context %></th>
			<th><%= casein_sort_link "ContextCN", :context_cn %></th>
			<th>&nbsp;</th>
		</tr>
	</thead>

	<% page_contents.each do |page_content| %>
		<tr>
			<td><%= casein_table_cell_link page_content.name, casein_page_content_path(page_content) %></td>
			<td><%= casein_table_cell_link image_tag(page_content.image.url(:medium), :size => "64"), casein_page_content_path(page_content) %></td>
			<td><%= casein_table_cell_link page_content.context, casein_page_content_path(page_content) %></td>
			<td><%= casein_table_cell_link page_content.context_cn, casein_page_content_path(page_content) %></td>
			<td class="delete">
				<%= link_to(casein_show_row_icon("trash"), casein_page_content_path(page_content), :method => :delete, :data => { :confirm => "Are you sure you want to delete this page content?" }) %>
			</td>
		</tr>
	<% end %>
</table>

app/views/casein/page_contents/index.html.erb
<!-- Scaffolding generated by Casein v5.1.1.5 -->

<h2>Page contents<%= casein_pagination_details @page_contents %></h2>

<%= render :partial => 'casein/page_contents/table', :locals => { :page_contents => @page_contents } %>

<div class="text-center">
	<%= will_paginate @page_contents %>
</div>

<%= content_for :sidebar do %>

	<li><%= link_to "#{casein_show_icon "plus-sign"}Add a new page content".html_safe, new_casein_page_content_path %></li>

<% end %>

app/views/casein/page_contents/new.html.erb
<!-- Scaffolding generated by Casein v5.1.1.5 -->

<h2>Add a new page content</h2>

<%= form_for @page_content, :url => casein_page_contents_path, :html => { multipart: true } do |f| %>

	<%= render :partial => 'casein/page_contents/form', :locals => { :f => f } %>

	<p class="submits">
		<%= link_to 'Cancel', casein_page_contents_path, :class => 'btn btn-mini btn-danger' %>
		<%= f.submit "Add new page content", :class => "btn btn-mini btn-primary" %>
	</p>

<% end %>

<%= content_for :sidebar do %>
	<li><%= link_to "#{casein_show_icon "th-list"}Back to list".html_safe, casein_page_contents_path %></li>
<% end %>

app/views/casein/page_contents/show.html.erb
<!-- Scaffolding generated by Casein v5.1.1.5 -->

<h2>View page content</h2>

<%= form_for @page_content, :url => casein_page_content_path(@page_content), :html => { multipart: true } do |f| %>

	<%= render :partial => 'casein/page_contents/form', :locals => { :f => f } %>

	<p class="submits">
	  	<%= link_to 'Cancel', casein_page_contents_path, :class => 'btn btn-mini btn-danger' %>
		<%= f.submit "Save changes", :class => "btn btn-mini btn-primary" %>
	</p>

<% end %>

<%= content_for :sidebar do %>
	<li><%= link_to "#{casein_show_icon "th-list"}Back to list".html_safe, casein_page_contents_path %></li>
<% end %>

app/views/categories/show.html.haml
%section.banner
  %a{:href => "#"}
    = image_tag("london_from_a_hot_air_balloon.jpg")
    .content.content-position.contain-padding
      %h1
        %span= @category.public_send("name#{@attr_suffix}".to_sym)

%section
  .contain-padding
    .row
      .col-md-8.text-detail.text-light
        = @category.public_send("context#{@attr_suffix}".to_sym).try(:html_safe)
        %br

      .col-md-4.side-text.text-light
        %h5 CONTACT DETAILS
        %address
          RSB Solictors
          %br/
          Unit 109, Cremer business centre
          %br/
          37 Cremer Street, London
          %br/
          E2 8HD

        %h5 PHONE NUMBER
        %address
          020 3092 5345

        %h5 EMAIL
        = mail_to "info@rsbsolicitors.co.uk"

        %h5 WECHAT
        %address
          TL07873963102

        = image_tag("qr-code.jpg", :size => "131x131", :alt => "RSB")
        %br/
        %br/

app/views/layouts/_footer.haml
%footer.footer.text-light
  .contain-padding
    .row
      .col-lg-3.col-md-6
        %ul
          %li
            %h5= link_to t("services").upcase, category_path(@services)
          - @services.children.sort.each do |first_tier|
            %li= link_to first_tier.public_send("name#{@attr_suffix}".to_sym), category_path(first_tier)
      .col-lg-3.col-md-6
        %ul
          %li
            %h5= link_to t("sectors").upcase, category_path(@sectors)
          - @sectors.children.sort.each do |first_tier|
            %li= link_to first_tier.public_send("name#{@attr_suffix}".to_sym), category_path(first_tier)
      .col-lg-3.col-md-6
        %ul
          %li
            %h5
              %a{:href => contact_path}= t("contact_us").upcase
          %li
            %a{:href => "mailto:info@rsbsolicitors.co.uk", :title => "Send an e-mail to UKEI"} info@rsbsolicitors.co.uk
          %br/
          %li
            %h5= link_to t("location").upcase, location_path("london")
            %address
              RSB Solictors
              %br/
              = @address.context
              %br/
              = "T: #{@landline.context}"
              %br/
              = "M: #{@mobile.context}"
          %li
            %h5= t("wechat").upcase
            TL07873963102

      .col-lg-3.col-md-6
        %ul
          %li
            %h5= t("connect").upcase
          %li= link_to "Wechat"
          %li= link_to "Weibo"
          %li= link_to "Facebook"
          %li= link_to "Linkedin"

          %br/
          %li
            %h5= t("social").upcase
          %li
            .row
              .col-md-2
                %i.fa.fa-wechat.fa-2x.fa-grey
              .col-md-2
                %i.fa.fa-weibo.fa-2x.fa-grey
          %li
            .row
              .col-md-2
                %i.fa.fa-facebook-square.fa-2x.fa-grey
              .col-md-2
                %i.fa.fa-linkedin.fa-2x.fa-grey

.footer_copy
  .contain-padding
    .row
      .col-lg-12{:role => "navigation"}
        %ul#menu-footer-navigation.menu
          %li
            %a{:href => root_path} © 2015 RSB
          %li.menu-terms-of-use
            %a{:href => terms_path} Terms of use
          %li.menu-privacy-policy
            %a{:href => privacy_path} Privacy policy

app/views/layouts/_nav.haml
.navbar.navbar-default.navbar-fixed-top{:role => "navigation"}
  .navbar-header
    %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
      %span.sr-only Toggle navigation
      %span.icon-bar
      %span.icon-bar
      %span.icon-bar
    %a.navbar-brand.logo-padding{:href => root_path}
      = image_tag(@logo.image.url, :size => "175x85")
  .collapse.navbar-collapse
    %ul.nav.navbar-nav.text-light.nav-margin
      - @categories.each do |category|
        - if category.children.empty?
          %li= link_to category.public_send("name#{@attr_suffix}".to_sym).try(:upcase), category_path(category)
        - else
          %li.dropdown-hover
            %a.dropdown-toggle{"data-toggle" => "dropdown"}
              = category.public_send("name#{@attr_suffix}".to_sym).try(:upcase)
              %span.caret
              %ul.dropdown-menu
                - category.children.sort.each do |first_tier|
                  - if first_tier.children.empty?
                    %li= link_to first_tier.public_send("name#{@attr_suffix}".to_sym).try(:capitalize), category_path(first_tier)
                  - else
                    %li.dropdown-submenu.dropdown-menu-right
                      %a
                        = first_tier.public_send("name#{@attr_suffix}".to_sym).try(:capitalize)
                        %i.fa.fa-caret-right
                      %ul.dropdown-menu.dropdown-hover
                        - first_tier.children.sort.each do |second_tier|
                          %li= link_to second_tier.public_send("name#{@attr_suffix}".to_sym).try(:capitalize), category_path(second_tier)
      %li= link_to t("china_desk").upcase, china_desk_path
      %li= link_to t("contact").upcase, contact_path

:javascript
  $(".dropdown-hover").hover((function() {
    return $(this).toggleClass("open");
  }), function() {
    return $(this).toggleClass("open");
  });

app/views/layouts/_shim.haml
/[if lt IE 9]
  %script{:src => "http://html5shim.googlecode.com/svn/trunk/html5.js"}

app/views/layouts/application.haml
!!!
%html
  %head
    %meta{:charset => "utf-8"}/
    %meta{:content => "IE=edge", "http-equiv" => "X-UA-Compatible"}/
    %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}/
    %title RSB Solicitors
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
    = render "layouts/shim"

  %body
    = render "layouts/nav"
    = yield
    = render "layouts/footer"

app/views/shared/_flash_messages.haml
- flash.each do |key, value|
  %p{:class => "bg-#{key}"}= value

app/views/static_pages/china_desk.haml
%section.banner
  %a{:href => "#"}
    = image_tag("london_from_a_hot_air_balloon.jpg")
    .content.content-position.contain-padding
      %h1
        %span China Desk

%section.text-light
  .contain-padding
    .content-text-position
      %p.text-detail
        London, one of the world’s most important commercial hubs, can be a financial, legal and cultural minefield for the uninitiated. However, experienced local advice can ensure you safely navigate the pitfalls. We provide a robust and comprehensive support framework to potential Chinese investors for all your business activities in the UK and Europe.
      .row
        .col-lg-4
          %h2 Head of China Desk
          .thumbnail.pretty-thumbnail
            %a{:href => location_path("london")}
              = image_tag("chinese-flag-graphic.png")
            .caption.text-detail
              %strong Tony Liu
              %p Head of China Desk
              %ul.list-unstyled
                %li
                  .row
                    .col-md-1
                      %i.fa.fa-envelope-o
                    .col-md-5
                      t.liu@rsbsolicitors.co.uk
                %li
                  .row
                    .col-md-1
                      %i.fa.fa-phone
                    .col-md-5
                      020 3092 5345
                %li
                  .row
                    .col-md-1
                      %i.fa.fa-wechat
                    .col-md-5
                      TL07873963102

        .col-lg-6.text-detail.col-lg-offset-2
          %h2 We advise on
          %ul
            %li Funds
            %li International dispute resolution
            %li Intellectual property
            %li Mergers & acquisitions
            %li Private wealth
            %li Real Estate
            %li Tax
            %li Corporate finance 
            %li Immigration
            %li Employment

app/views/static_pages/contact.haml
%section.banner
  .content.contain-padding
    .content-text-position
      %h2
        %span CONTACT
      %h1
        %span Meet our team

    .row
      .col-sm-6.col-md-4
        .thumbnail.pretty-thumbnail
          %a{:href => location_path("london")}
            %img{:src => "https://sixpillarstopersia.files.wordpress.com/2012/07/fb_logo1.png", :width => "260"}/
          .caption
            %a{:href => location_path("london")}
              %h3 London
            %address
              %strong RSB Solictors
              %br/
              Unit 109, Cremer business centre
              %br/
              37 Cremer Street, London
              %br/
              E2 8HD
              %br/
              %abbr{:title => "Phone"} P:
              020 3092 5345
      .col-sm-6.col.md-8
        %iframe{:frameborder => "0", :height => "443", :marginheight => "0", :marginwidth => "0", :scrolling => "no", :src => "https://maps.google.com/maps?hl=en&q=44 Bishopsgate london EC2N 4AH&ie=UTF8&t=roadmap&z=18&iwloc=B&output=embed", :width => "688"}

app/views/static_pages/home.haml
%section.banner
  %a{:href => "#"}
    = image_tag("london_from_a_hot_air_balloon.jpg")
    .content.content-position.contain-padding
      %h1
        %span= @slogen.public_send("context#{@attr_suffix}".to_sym)

.home-bg
  %section
    .contain-padding
      %p.intro.text-light= @home_intro.public_send("context#{@attr_suffix}".to_sym).try(:html_safe)
      %br
      %br

app/views/static_pages/location.haml
%section.banner
  %a{:href => "#"}
    = image_tag("london_from_a_hot_air_balloon.jpg")
    .content.content-position.contain-padding
      %h2
        %span= @area
      %h1
        %span Meet our team

%section
  .contain-padding
    .row
      .col-md-8
        %p.text-detail
          From Brandcell’s office, Livework’s Beirut partner, we deliver innovative solutions to our clients ever-changing challenges. Our studio Brandcell is located right in the heart of the city, steps away from the Beirut Financial District and the trendy Mar Mikhael area; and right across the street from the best falafel joint in the country. Let’s collaborate!

        %h3
          Arriving by plane:

        %p.text-normal
          It’s better to arrange for a pick up service with your hotel before travelling to Beirut, to avoid being preyed upon by eager taxi drivers at the arrival lounge. We’re a 20 minute car ride away, on the crossroad of “Damascus” and “Bechara Khoury”.

      .col-md-4
        %h5 CONTACT DETAILS
        %address
          %strong RSB Solictors
          %br/
          Unit 109, Cremer business centre
          %br/
          37 Cremer Street, London
          %br/
          E2 8HD

        %h5 Phone Number
         %address
          020 3092 5345

        %h5
          Email
        = mail_to "info@rsbsolicitors.co.uk"

        %h5
          CONTACT

        %strong Full Name
        %br/
        %a{:href => "mailto:#"} first.last@example.com

app/views/static_pages/terms.haml
%section.banner
  .content.contain-padding
    .content-text-position
      %h1
        %span Terms and conditions

      .text-detail
        %p Welcome to our website. If you continue to browse and use this website, you are agreeing to comply with and be bound by the following terms and conditions of use, which together with our privacy policy govern RSB Solicitors's relationship with you in relation to this website. If you disagree with any part of these terms and conditions, please do not use our website.
        %p The term 'RSB Solicitors' or 'us' or 'we' refers to the owner of the website whose registered office is 44 Bishopsgate, London, United Kingdom. Our company registration number is [company registration number and place of registration]. The term 'you' refers to the user or viewer of our website.
        %p The use of this website is subject to the following terms of use:
        %ul
          %li The content of the pages of this website is for your general information and use only. It is subject to change without notice.
          %li This website uses cookies to monitor browsing preferences. If you do allow cookies to be used, the following personal information may be stored by us for use by third parties: [insert list of information].
          %li Neither we nor any third parties provide any warranty or guarantee as to the accuracy, timeliness, performance, completeness or suitability of the information and materials found or offered on this website for any particular purpose. You acknowledge that such information and materials may contain inaccuracies or errors and we expressly exclude liability for any such inaccuracies or errors to the fullest extent permitted by law.
          %li Your use of any information or materials on this website is entirely at your own risk, for which we shall not be liable. It shall be your own responsibility to ensure that any products, services or information available through this website meet your specific requirements.
          %li This website contains material which is owned by or licensed to us. This material includes, but is not limited to, the design, layout, look, appearance and graphics. Reproduction is prohibited other than in accordance with the copyright notice, which forms part of these terms and conditions.
          %li All trade marks reproduced in this website which are not the property of, or licensed to, the operator are acknowledged on the website.
          %li Unauthorised use of this website may give rise to a claim for damages and/or be a criminal offence.
          %li From time to time this website may also include links to other websites. These links are provided for your convenience to provide further information. They do not signify that we endorse the website(s). We have no responsibility for the content of the linked website(s).
          %li Your use of this website and any dispute arising out of such use of the website is subject to the laws of England, Northern Ireland, Scotland and Wales.